# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a6957e001f7c0180e22f3e6e13f8da5818e106286d1ac17e1ad15db841540335b2dcb389c8ba8d1037a253fd6548f44af70ecfe5e3aab24cfc95c0c85b8b29

test:
  secret_key_base: febcce69ceaa4de4edbdb311f7d88e95ddc309834d98dbcd8f660feb2480430662c31278c639cb1d0d7a23a11736a16ef6603803d68be9981f14ff52a6bf2d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
